Remove identifier system extension
The identifier system defined as it was causes the latest version of the ig publisher to choke:
```
java.lang.NullPointerException: Cannot invoke "String.hashCode()" because "<local4>" is null
	at org.hl7.fhir.r5.renderers.DataRenderer.renderIdentifier(DataRenderer.java:1254)
	at org.hl7.fhir.r5.renderers.DataRenderer.render(DataRenderer.java:710)
	at org.hl7.fhir.r5.renderers.PatientRenderer.describe(PatientRenderer.java:266)
	at org.hl7.fhir.r5.renderers.PatientRenderer.describe(PatientRenderer.java:218)
	at org.hl7.fhir.r5.renderers.PatientRenderer.render(PatientRenderer.java:274)
	at org.hl7.fhir.r5.renderers.ResourceRenderer.render(ResourceRenderer.java:101)
	at org.hl7.fhir.igtools.publisher.Publisher.generateNarratives(Publisher.java:2066)
	at org.hl7.fhir.igtools.publisher.Publisher.loadConformance(Publisher.java:5693)
	at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:1134)
	at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:980)
	at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:12505)
```
This affects the `master` branch too.